[package]
name = "dioteko-raylib-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[build-dependencies]
cmake = { git = "https://github.com/alexcrichton/cmake-rs.git", branch = "master" }
